export default {
  sounds: {
    firstNote: new AudioClip("sounds/firstNote.mp3"),
    forthNote: new AudioClip("sounds/forthNote.mp3"),
    gateOpening: new AudioClip("sounds/gateOpening.mp3"),
    ligtningOrb: new AudioClip("sounds/lightningOrb.mp3"),
    mirrorMove: new AudioClip("sounds/mirrorMove.mp3"),
    nightAmbience: new AudioClip("sounds/nightAmbience.mp3"),
    secondNote: new AudioClip("sounds/secondNote.mp3"),
    orbPickup: new AudioClip("sounds/orbPickup.mp3"),
    orbSpawn: new AudioClip("sounds/orbSpawn.mp3"),
    statueMove: new AudioClip("sounds/statueMove.mp3"),
    thirdNote: new AudioClip("sounds/thirdNote.mp3"),
    portalOpen: new AudioClip("sounds/portalOpen.mp3"),
    portal: new AudioClip("sounds/portal.mp3"),
  },
  models: {
    earthFirePuzzles: {
      resetSwitch: new GLTFShape("models/earthFirePuzzles/resetSwitch.glb"),
      statueEarth: new GLTFShape("models/earthFirePuzzles/statueEarth.glb"),
      statueEarthGlow: new GLTFShape("models/earthFirePuzzles/statueEarthGlow.glb"),
      statueFire: new GLTFShape("models/earthFirePuzzles/statueFire.glb"),
      statueFireGlow: new GLTFShape("models/earthFirePuzzles/statueFireGlow.glb"),
      statueFireGlowRotated: new GLTFShape("models/earthFirePuzzles/statueFireGlowRotated.glb"),
      statueFireRotated: new GLTFShape("models/earthFirePuzzles/statueFireRotated.glb"),
      statueSelectorGlow: new GLTFShape("models/earthFirePuzzles/statueSelectorGlow.glb"),
      statueSelectorHand: new GLTFShape("models/earthFirePuzzles/statueSelectorHand.glb"),
    },
    standard: {
      base: new GLTFShape("models/standard/base.glb"),
      building: new GLTFShape("models/standard/building.glb"),
      earthGate: new GLTFShape("models/standard/earthGate.glb"),
      fire: new GLTFShape("models/standard/fire.glb"),
      waterGate: new GLTFShape("models/standard/waterGate.glb"),
    },
    waterPuzzle: {
      mirrorScaledColliders: new GLTFShape("models/waterPuzzle/mirrorScaledColliders.glb"),
      mirrorScaledCollidersRotated: new GLTFShape("models/waterPuzzle/mirrorScaledCollidersRotated.glb"),
      mirrorSelector: new GLTFShape("models/waterPuzzle/mirrorSelector.glb"),
      mirrorSelectorGlow: new GLTFShape("models/waterPuzzle/mirrorSelectorGlow.glb"),
      mirrorSelectorHand: new GLTFShape("models/waterPuzzle/mirrorSelectorHand.glb"),
      rayOffsetY: new GLTFShape("models/waterPuzzle/rayOffsetY.glb"),
      rayTarget: new GLTFShape("models/waterPuzzle/rayTarget.glb"),
    },
    windPuzzle: {
      floatingEarthRock: new GLTFShape("models/windPuzzle/floatingEarthRock.glb"),
      floatingEarthRockGlow: new GLTFShape("models/windPuzzle/floatingEarthRockGlow.glb"),
      floatingFireRock: new GLTFShape("models/windPuzzle/floatingFireRock.glb"),
      floatingFireRockGlow: new GLTFShape("models/windPuzzle/floatingFireRockGlow.glb"),
      floatingWaterRock: new GLTFShape("models/windPuzzle/floatingWaterRock.glb"),
      floatingWaterRockGlow: new GLTFShape("models/windPuzzle/floatingWaterRockGlow.glb"),
      floatingWindRock: new GLTFShape("models/windPuzzle/floatingWindRock.glb"),
      floatingWindRockGlow: new GLTFShape("models/windPuzzle/floatingWindRockGlow.glb"),
      lightningOrb: new GLTFShape("models/windPuzzle/lightningOrb.glb"),
      orbEffect: new GLTFShape("models/windPuzzle/orbEffect.glb"),
      ray: new GLTFShape("models/windPuzzle/ray.glb"),
      portalMain: new GLTFShape("models/windPuzzle/portalMain.glb"),
      portalStrips: new GLTFShape("models/windPuzzle/portalStrips.glb"),
      portalSwirls: new GLTFShape("models/windPuzzle/portalSwirls.glb"),
    },
  }
}
